version: 2
jobs:
  build:
    docker:
      - image: node:7

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      # - run: yarn lint
      - run: yarn test

      - run:
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn build
            else
              echo "Skip building site"
            fi

      - add_ssh_keys:
          fingerprints:
            - "93:c9:7e:ae:3c:09:4c:ba:5c:a5:77:02:0e:07:e0:bb"

      - run:
          name: Deploy to GH Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd build
              echo ruralaccess.info > CNAME
              git init
              git config user.name "Devseed-CI"
              git config user.email "dev@developmentseed.org"
              git add .
              git commit -m "CI deploy [skip ci]"
              git remote add origin git@github.com:developmentseed/ds-pipe.git
              git push origin --force --quiet HEAD:gh-pages
              rm -rf .git
            else
              echo "Skip deploying to Github"
            fi